---

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

- name: Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
    suffix: ".gnome_extension_download"
  register: r_gnome_extension_download_dir
  changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

- block:
    - name: Download Gnome Shell extension - {{ gnome_extension_info.name }}
      ansible.builtin.get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      register: r_gnome_extension_download

    - name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
      ansible.builtin.command: gnome-extensions install {{ r_gnome_extension_download.dest }}
  always:
    - name: Delete temporary download directory
      ansible.builtin.file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

