galaxy_info:
  author: Jared Hocutt
  description: >-
    Applies the common configurations that I use for my workstations.

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Fedora
      versions:
        - 33

  galaxy_tags: []

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
