namespace: jaredhocutt
name: workstation
description: A collection of roles used to bootstrap my workstations

version: 1.0.0

dependencies:
  community.general: "*"

readme: README.md
authors:
  - Jared Hocutt (@jaredhocutt)

repository: https://github.com/jaredhocutt-collections/workstation
license:
  - MIT

tags: []
build_ignore: []
