---
# tasks file for dotfiles

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - git
      - stow
      - xclip
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install required packages
  community.general.homebrew:
    name:
      - git
      - stow
      - xclip
    state: present
  when: ansible_os_family == "Darwin"

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:jaredhocutt/dotfiles.git
    dest: ~/.dotfiles
    update: yes
    accept_hostkey: yes

- include_tasks: enable.yml
  loop: "{{ dotfiles_enabled }}"
