galaxy_info:
  author: Jared Hocutt (@jaredhocutt)
  description: >-
    Configures the Visual Studio Code repository and Installs Visual Studio Code.

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Fedora
      versions:
        - 33

  galaxy_tags:
    - code
    - vscode
    - visual-studio

dependencies: []
