galaxy_info:
  author: Jared Hocutt (@jaredhocutt)
  description: >-
    Installs Ferdi.

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Fedora
      versions:
        - 33

  galaxy_tags:
    - ferdi
    - franz
    - chat

dependencies: []
