---

- name: Install required packages for dconf module
  ansible.builtin.dnf:
    name:
      - dconf
      - dbus-tools
      - dbus-daemon
    state: present
  become: yes

- name: Set dconf setting
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ dconf_settings }}"
