
---

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ casks }}"
