---
# tasks file for common

- ansible.builtin.import_tasks: selinux.yml

- ansible.builtin.import_tasks: packages.yml

- ansible.builtin.import_tasks: flatpaks.yml

- ansible.builtin.import_tasks: services.yml

- ansible.builtin.import_tasks: grub.yml

- ansible.builtin.import_tasks: display.yml

- ansible.builtin.import_tasks: networking.yml

- ansible.builtin.import_tasks: dconf_settings.yml
