
---

- name: Install distribution GPG keys
  ansible.builtin.dnf:
    name: distribution-gpg-keys
    state: present
  become: yes

- name: Find RPM Fusion GPG keys
  ansible.builtin.find:
    paths: /usr/share/distribution-gpg-keys/rpmfusion
    follow: yes
  register: r_rpmfusion_gpg_keys

- name: Import RPM Fusion GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item.path }}"
    state: present
  become: yes
  loop: "{{ r_rpmfusion_gpg_keys.files }}"

- name: Check for existing RPM Fusion repositories
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: r_rpmfusion_check_existing

- name: Install RPM Fusion repositories
  ansible.builtin.dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    update_cache: yes
    state: present
  become: yes
  when: not r_rpmfusion_check_existing.stat.exists

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Configure kernel install limit
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^installonly_limit="
    line: installonly_limit={{ kernel_install_limit }}
    state: present
  become: yes
