
---

- name: Check for existing RPM Fusion repositories
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: r_rpmfusion_check_existing

- name: Install RPM Fusion repositories
  ansible.builtin.dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  become: yes
  when: not r_rpmfusion_check_existing.stat.exists

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Configure kernel install limit
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: "^installonly_limit="
    line: installonly_limit={{ kernel_install_limit }}
    state: present
  become: yes
