---

- name: Start and enable system services
  ansible.builtin.service:
    name: "{{ item }}"
    scope: system
    state: started
    enabled: yes
  become: yes
  loop: "{{ services }}"

- name: Start and enable user services
  ansible.builtin.service:
    name: "{{ item }}"
    scope: user
    state: started
    enabled: yes
  loop: "{{ user_services }}"
